# Generated by Django 5.1.7 on 2025-04-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_brand_product_category_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('kids', 'Kids'), ('men', 'Men'), ('women', 'Women')], default='kids', max_length=10),
        ),
    ]
